meta_product_name: "Servicios Ya!"
meta_title: "Servicios Ya! La manera m치s simple de contratar un servicio."
meta_description: "Encontr치 la soluci칩n que est치s necesitando"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@serviciosya.shop"
